// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAITf9ouwTJy8lQFG7jIVlnr1lWWeSHDIo',
    appId: '1:863719171616:web:acc7cc30a90f3bbe37be45',
    messagingSenderId: '863719171616',
    projectId: 'mp-fp-financetracker',
    authDomain: 'mp-fp-financetracker.firebaseapp.com',
    storageBucket: 'mp-fp-financetracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-OXKfBsB9d32sinP_aRQMyr82Ptc_iUg',
    appId: '1:863719171616:android:c66957b1215eec1b37be45',
    messagingSenderId: '863719171616',
    projectId: 'mp-fp-financetracker',
    storageBucket: 'mp-fp-financetracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZFWm6LOyCk1Bj_XrIpB2q872wbSOgrI0',
    appId: '1:863719171616:ios:54f184ac5084fa1637be45',
    messagingSenderId: '863719171616',
    projectId: 'mp-fp-financetracker',
    storageBucket: 'mp-fp-financetracker.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZFWm6LOyCk1Bj_XrIpB2q872wbSOgrI0',
    appId: '1:863719171616:ios:54f184ac5084fa1637be45',
    messagingSenderId: '863719171616',
    projectId: 'mp-fp-financetracker',
    storageBucket: 'mp-fp-financetracker.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAITf9ouwTJy8lQFG7jIVlnr1lWWeSHDIo',
    appId: '1:863719171616:web:7f2e56601f0dca0737be45',
    messagingSenderId: '863719171616',
    projectId: 'mp-fp-financetracker',
    authDomain: 'mp-fp-financetracker.firebaseapp.com',
    storageBucket: 'mp-fp-financetracker.firebasestorage.app',
  );
}
